#!/usr/bin/env ruby

require 'rbbt-util'
require 'rbbt/util/simpleopt'

$0 = "rbbt #{$previous_commands*" "} #{ File.basename(__FILE__) }" if $previous_commands

options = SOPT.setup <<EOF

Bootstrap HTSBenchmark workflow

$ #{$0} [options] 

Use - to read from STDIN

-h--help Print this help

EOF
if options[:help]
  if defined? rbbt_usage
    rbbt_usage 
  else
    puts SOPT.doc
  end
  exit 0
end

Workflow.require_workflow "Sequence"

job = Sequence.job(:lift_over, "Bootstrap", :positions => ["1:10000:A"], :source => HTSBenchmark::HG19_ORGANISM, :target => HTSBenchmark::HG38_ORGANISM)
job.produce
job.recursive_clean

Workflow.require_workflow "HTSBenchmark"

job = HTSBenchmark.job(:simulate_normal)
job.produce

